### ISSUE TITLE
Multiplayer Custom Races?

### ISSUE THREAD

**Issue by meltirogue** [my-name-is-samael/BeamJoy#17]
This is a question more than a ticket, I have created a custom race but it only shows up in solo race and I don't see it in the race drop down I'm just trying to race my buddy

**Comment by my-name-is-samael** [comment]
You have to create multiple start positions for your race (then your race will appear in the vote menu), and one of you need to have the _VoteServerScenario_ permission to start a vote, or the _Scenario_ permission (which you should have) and start the race in the vote menu.
I know this is pretty confusing right now, but the upcoming datapack will give example of all scenarios to understand. Video tutorials will also come out soon after the datapack.

**Comment by Melti-Rogue** [comment]
oh my goodness i didnt even think of that thank you much!
