### ISSUE TITLE
Players cannot vote to start races

### ISSUE THREAD

**Issue by Shedlow** [my-name-is-samael/BeamJoy#23]
Players cannot see the 'Vote' button in the BeamJoyInterface, these players are in both the None group and the Players group, I had a look at adding permissions to the groups but from all of the ones that I added players cannot cast a vote? but I am able to as the owner and it works perfectly fine.

**Comment by my-name-is-samael** [comment]
@Shedlow Tested today, it is working fine
By default, the permission `VoteServerScenario` is given to `player`+ groups. If you want your new players to be able to spawn a vehicle and start a race vote, you need to give the group `none` a `VehicleCap` or 1 at least, and give the `VoteServerScenario` to `none` group.
Also you race(s) must have multiple start positions to be considered as multiplayer races (the amount of start positions define the race player cap).

**Comment by Shedlow** [comment]
Thank you for all of the information.

Resolved!
