### ISSUE TITLE
Economy

### ISSUE THREAD

**Issue by Ainazik23** [my-name-is-samael/BeamJoy#28]
will it be difficult to add economics to this plugin? That is, to get paid for the work, teams for admins so that they can add game currency to the player, and so on

**Comment by my-name-is-samael** [comment]
It is not difficult, but a currency is useless if you have nothing to pay. The point of the mod is to bring solo features to players, not to create a RP environment (even if configuration can give you a good start point). Feel free to fork the mod and implements currency system, or look for actual forks, as [SiRP](https://github.com/KaMiKaZeE1221/SiRP)
