### ISSUE TITLE
PersistMP compatibility issue

### ISSUE THREAD

**Issue by KaMiKaZeE1221** [my-name-is-samael/BeamJoy#32]
Before I get in to this, I completely understand if you want nothing to do with this, but your help would be nice.

This script works fine without BeamJoy, however once BeamJoy is loaded it throws an error on the client script line "27" where it actually tries to spawn the vehicle.

All I'm after is some guidance towards making this play nice with BeamJoy

**Server** - https://thesaltygamers.net/TSG-Files/wADo1/GINuxebE74.lua
**Client** - https://thesaltygamers.net/TSG-Files/wADo1/xuQeMaHU09.lua

**Comment by my-name-is-samael** [comment]
Oh I see, this script allows you to keep state of players vehicles and reload them on reconnection.
I will need the complete error stacktrace to identify where the problem is, I guess.

Also I think you should write this feature within your BeamJoy fork, since this feature is pretty easy to implement.

**Comment by KaMiKaZeE1221** [comment]
Here is the error, also I know very little, implementing anything within BeamJoy is still hard for me 😂

662.71542|E|GameEngineLua:Exception| [string "lua/ge/extensions/PersistMP.lua"]:27: attempt to index a nil value
=============== Stack Traceback >> START >>
(1) metamethod C function '__index'
(2) Lua field 'func' at line 27 of chunk 'lua/ge/extensions/PersistMP.lua'
  json = string[700/5077]: "{\"Vehicles\":[{\"config\":{\"ign\":3,\"jbm\":\"scintilla\",\"pid\":0,\"pos\":[293.55801391602,-444.72799682617,103.92800140381],\"rot\":[0,0,0,1],\"vcf\":{\"mainPartName\":\"scintilla\",\"model\":\"scintilla\",\"paints\":[{\"baseColor\":[0.8759999871254,0,0,2],\"clearcoat\":1,\"clearcoatRoughness\":0.029999999329448,\"metallic\":1,\"roughness\":0.64999997615814},{\"baseColor\":[0.8759999871254,0,0,2],\"clearcoat\":1,\"clearcoatRoughness\":0.029999999329448,\"metallic\":1,\"roughness\":0.64999997615814},{\"baseColor\":[0.25499999523162997,0.090999998152256,0.19799999892712,2],\"clearcoat\":1,\"clearcoatRoughness\":0.029999999329448,\"metallic\":1,\"roughness\":0.64999997615814}],\"partConfigFilename\":\"vehicles/scintilla/gts.pc\",\"parts\":{\"brakepad_F\"" (more...)
  vehName = string[9]: "scintilla"
  vehConfigFile = string[25]: "vehicles/scintilla/gts.pc"
  pos = table: 0x0249401875e8  {1:292.85445346711, 2:-444.49131751384, 3:100.45821148535}
  rot = table: 0x02494eed66f8  {1:-0.0013382797421821, 2:-0.0015889901254199, 3:-0.73958969157236, 4:0.67305480626589 (more...)}
  (*temporary) = nil
  (*temporary) = number: 1.2419e-311
  (*temporary) = nil
  (*temporary) = number: 0
  (*temporary) = nil
  (*temporary) = table: 0x024927f0dbe0  {1:table: 0x024927f0dc60, 2:table: 0x024927f0dca8, getPhysicsSpeedFactor:function: 0x024927f90fa0 (more...)}
  (*temporary) = string[21]: "errors.cannotSpawnVeh"
  (*temporary) = nil
  (*temporary) = Lua function '?' (defined at line 16 of chunk lua/ge/extensions/BJI/managers/ToastManager.lua)
  (*temporary) = number: 1.24202e-311
  (*temporary) = string[28]: "attempt to index a nil value"
(3) Lua upvalue 'handleEvents' at line 162 of chunk 'lua/ge/extensions/MPGameNetwork.lua'
  p = string[700/5112]: ":onPersistMP_GetAndApplyStoredInfo:{\"Vehicles\":[{\"config\":{\"ign\":3,\"jbm\":\"scintilla\",\"pid\":0,\"pos\":[293.55801391602,-444.72799682617,103.92800140381],\"rot\":[0,0,0,1],\"vcf\":{\"mainPartName\":\"scintilla\",\"model\":\"scintilla\",\"paints\":[{\"baseColor\":[0.8759999871254,0,0,2],\"clearcoat\":1,\"clearcoatRoughness\":0.029999999329448,\"metallic\":1,\"roughness\":0.64999997615814},{\"baseColor\":[0.8759999871254,0,0,2],\"clearcoat\":1,\"clearcoatRoughness\":0.029999999329448,\"metallic\":1,\"roughness\":0.64999997615814},{\"baseColor\":[0.25499999523162997,0.090999998152256,0.19799999892712,2],\"clearcoat\":1,\"clearcoatRoughness\":0.029999999329448,\"metallic\":1,\"roughness\":0.64999997615814}],\"partConfigFilename\":\"vehicles/scin" (more...)
  eventName = string[33]: "onPersistMP_GetAndApplyStoredInfo"
  eventData = string[700/5077]: "{\"Vehicles\":[{\"config\":{\"ign\":3,\"jbm\":\"scintilla\",\"pid\":0,\"pos\":[293.55801391602,-444.72799682617,103.92800140381],\"rot\":[0,0,0,1],\"vcf\":{\"mainPartName\":\"scintilla\",\"model\":\"scintilla\",\"paints\":[{\"baseColor\":[0.8759999871254,0,0,2],\"clearcoat\":1,\"clearcoatRoughness\":0.029999999329448,\"metallic\":1,\"roughness\":0.64999997615814},{\"baseColor\":[0.8759999871254,0,0,2],\"clearcoat\":1,\"clearcoatRoughness\":0.029999999329448,\"metallic\":1,\"roughness\":0.64999997615814},{\"baseColor\":[0.25499999523162997,0.090999998152256,0.19799999892712,2],\"clearcoat\":1,\"clearcoatRoughness\":0.029999999329448,\"metallic\":1,\"roughness\":0.64999997615814}],\"partConfigFilename\":\"vehicles/scintilla/gts.pc\",\"parts\":{\"brakepad_F\"" (more...)
  (for index) = number: 1
  (for limit) = number: 3
  (for step) = number: 1
  i = number: 1
(4) Lua function '?' at line 279 of chunk 'lua/ge/extensions/MPGameNetwork.lua'
  params = string[700/5112]: ":onPersistMP_GetAndApplyStoredInfo:{\"Vehicles\":[{\"config\":{\"ign\":3,\"jbm\":\"scintilla\",\"pid\":0,\"pos\":[293.55801391602,-444.72799682617,103.92800140381],\"rot\":[0,0,0,1],\"vcf\":{\"mainPartName\":\"scintilla\",\"model\":\"scintilla\",\"paints\":[{\"baseColor\":[0.8759999871254,0,0,2],\"clearcoat\":1,\"clearcoatRoughness\":0.029999999329448,\"metallic\":1,\"roughness\":0.64999997615814},{\"baseColor\":[0.8759999871254,0,0,2],\"clearcoat\":1,\"clearcoatRoughness\":0.029999999329448,\"metallic\":1,\"roughness\":0.64999997615814},{\"baseColor\":[0.25499999523162997,0.090999998152256,0.19799999892712,2],\"clearcoat\":1,\"clearcoatRoughness\":0.029999999329448,\"metallic\":1,\"roughness\":0.64999997615814}],\"partConfigFilename\":\"vehicles/scin" (more...)
(5) Lua local 'func' at line 308 of chunk 'lua/ge/extensions/MPGameNetwork.lua'
  dt = number: 0.0230431
  received = string[700/5113]: "E:onPersistMP_GetAndApplyStoredInfo:{\"Vehicles\":[{\"config\":{\"ign\":3,\"jbm\":\"scintilla\",\"pid\":0,\"pos\":[293.55801391602,-444.72799682617,103.92800140381],\"rot\":[0,0,0,1],\"vcf\":{\"mainPartName\":\"scintilla\",\"model\":\"scintilla\",\"paints\":[{\"baseColor\":[0.8759999871254,0,0,2],\"clearcoat\":1,\"clearcoatRoughness\":0.029999999329448,\"metallic\":1,\"roughness\":0.64999997615814},{\"baseColor\":[0.8759999871254,0,0,2],\"clearcoat\":1,\"clearcoatRoughness\":0.029999999329448,\"metallic\":1,\"roughness\":0.64999997615814},{\"baseColor\":[0.25499999523162997,0.090999998152256,0.19799999892712,2],\"clearcoat\":1,\"clearcoatRoughness\":0.029999999329448,\"metallic\":1,\"roughness\":0.64999997615814}],\"partConfigFilename\":\"vehicles/sci" (more...)
  status = nil
  partial = nil
  code = string[1]: "E"
  data = string[700/5112]: ":onPersistMP_GetAndApplyStoredInfo:{\"Vehicles\":[{\"config\":{\"ign\":3,\"jbm\":\"scintilla\",\"pid\":0,\"pos\":[293.55801391602,-444.72799682617,103.92800140381],\"rot\":[0,0,0,1],\"vcf\":{\"mainPartName\":\"scintilla\",\"model\":\"scintilla\",\"paints\":[{\"baseColor\":[0.8759999871254,0,0,2],\"clearcoat\":1,\"clearcoatRoughness\":0.029999999329448,\"metallic\":1,\"roughness\":0.64999997615814},{\"baseColor\":[0.8759999871254,0,0,2],\"clearcoat\":1,\"clearcoatRoughness\":0.029999999329448,\"metallic\":1,\"roughness\":0.64999997615814},{\"baseColor\":[0.25499999523162997,0.090999998152256,0.19799999892712,2],\"clearcoat\":1,\"clearcoatRoughness\":0.029999999329448,\"metallic\":1,\"roughness\":0.64999997615814}],\"partConfigFilename\":\"vehicles/scin" (more...)
(6) Lua field 'hook' at line 715 of chunk 'lua/common/extensions.lua'
  funcName = string[8]: "onUpdate"
  funcList = table: 0x02492cd24600  {1:function: 0x024932917860, 2:function: 0x024932d03688, 3:function: 0x024932c40468 (more...)}
  (for generator) = C function: builtin#6
  (for state) = table: 0x02492cd24600  {1:function: 0x024932917860, 2:function: 0x024932d03688, 3:function: 0x024932c40468 (more...)}
  (for control) = number: 8
  _ = number: 8
  func = Lua function '?' (defined at line 293 of chunk lua/ge/extensions/MPGameNetwork.lua)
(7) Lua function 'update' at file '/lua/ge/main.lua:536' (best guess)
  dtReal = number: 0.0230431
  dtSim = number: 0.0240066
  dtRaw = number: 1
--------------- << END <<

**Comment by my-name-is-samael** [comment]
With `PersistMP.lua":27: attempt to index a nil value` error, I would tell :
- `pos` is nil (which is less probable considering backend only sends data if it exists)
- `be:getPlayerVehicle(0)` is nil because the script didn't wait for the vehicle to spawn before setting its position. Fix would be to send position with the spawn data:
l.26: `core_vehicles.spawnNewVehicle(vehName, {config = vehConfigFile, pos = pos, rot = rot})`
or replace lines 26 and 27 by:
`BJIVeh.replaceOrSpawnVehicle(vehName, data.Vehicles[1].config.vcf.partConfigFilename, { pos = pos, rot = rot })` (I recommend to check for modified vehicles, and not saved configs)

Once again, I greatly suggest you to write your own implementation within BeamJoy, steps are:
- [BACKEND] Read into user data for vehicle and location with default values (PlayerManager.lua:instantiatePlayer:93)
- [BACKEND] Send those data through USER cache (PlayerManager.lua:getCacheUser:309)
- [FRONTEND] Retrieve-parse those data and spawn vehicle(s) at given position(s) (CacheManager.lua:parseCache:117)
- [BACKEND] On tick, retrieve and save players positions (TickManager.lua:_BJCSlowTick:6)
- [BACKEND] On player spawn or edit vehicle, save vehicle data to user (VehicleManager.lua:_BJCOnVehicleSpawn:9 & VehicleManager.lua:_BJCOnVehicleEdited:124)
- [BACKEND] On player disconnect, save user vehicle and coordinates to its DB file (PlayerManager.lua:_BJCOnPlayerDisconnect:231)

(line numbers are taken from this repo current state)
Take it step by step, debugging all you need with `BJIDEBUG = <data_you_want_to_monitor>` in game console, it will open a dedicated window and print your variables and data
