### ISSUE TITLE
possible new console commands

### ISSUE THREAD

**Issue by Melti-Rogue** [my-name-is-samael/BeamJoy#33]
could we get a bj restart maybe some other simple conmsole side commands sometimes im lazy and want to manage my server from my comfy chair lol

**Comment by my-name-is-samael** [comment]
It is not possible since the beammp stop command only stop the server. For it to work, you need to have an active server reboot system (in shell for example)

**Comment by my-name-is-samael** [comment]
Please add details for other useful console commands

**Comment by Melti-Rogue** [comment]
/countdown with a visual pop up center screen,  /change mape <map label> / voterace <race name>

**Comment by my-name-is-samael** [comment]
are we still talking about console commands or chat commands ?

**Comment by meltirogue** [comment]
I'm sorry, both honestly I personally rely on  my console but my guys in server like to use in game commands but sometimes I will do their race timers while I'm not in server short answer both if possible

**Comment by my-name-is-samael** [comment]
`voterace` is too complicated (too many mandatory and optional parameters)
`countdown` is not a part of the current gameplay, I will not include right now

`bj map <map_name>` is interesting, WIP

**Comment by my-name-is-samael** [comment]
`bj map <map_name>` will be in 1.1.2

**Comment by my-name-is-samael** [comment]
new commands implemented in today's release (1.1.3)
`voterace` is too complicated
`countdown` is not part of the gameplay yet, and depends on the user UI Apps layout
