### ISSUE TITLE
server not starting back up after restart command

### ISSUE THREAD

**Issue by Melti-Rogue** [my-name-is-samael/BeamJoy#34]
if given the restart command from within server to change map or just resart server it doesnt come back up

**Comment by Melti-Rogue** [comment]
personally my temp fix was to write a batch file that looks for the beam mp server executeable every 5 seconds works for no i appreciate all of your work

**Comment by my-name-is-samael** [comment]
Please take a look at my builder (`deleveopment/buildLoop.cmd`) for an active reboot system example. As said in #33 , the default beammp exit command is not capable of restarting itself
