### ISSUE TITLE
Changing main window title

### ISSUE THREAD

**Issue by n1kxzz** [my-name-is-samael/BeamJoy#35]
Hello dear Samael, we would like to change the title of the plugin. Help me how to do it. For example RatedRP(by Samael)
![image](https://github.com/user-attachments/assets/2e125984-3c23-4942-bfb2-fa85a27f8451)

**Comment by my-name-is-samael** [comment]
Hi,

You can change every single label in the mod to your wish, to do so, you can find all langs files in `Server/BeamJoyCore/lang/`. This specific message is located in `client.windows.BJI`
