### ISSUE TITLE
errors in update  0.34

### ISSUE THREAD

**Issue by futuregraphicart** [my-name-is-samael/BeamJoy#40]
![beamng-error-034](https://github.com/user-attachments/assets/e8305f79-5aba-44ee-80c2-5fcd27ebc6b7)
hey thanks for the mod. i am getting some errors when i try to start a race. i think the new 0.34 update did something to beamjoy. not sure could you look into it.  thanks

**Comment by my-name-is-samael** [comment]
Yeah I noticed it before the update with a beta tester, 1.1.2 will fix it 🤞

**Comment by my-name-is-samael** [comment]
Duplicates #37
