### ISSUE TITLE
v0.34 error

### ISSUE THREAD

**Issue by KaMiKaZeE1221** [my-name-is-samael/BeamJoy#42]
Getting this error, it doesn't seem to stop anything from working from what I can tell, but may need to be fixed, seems to happen when spawning a vehicle.

(EDIT)
This error seems to cause issues with teleporting to people via the interface, BJ thinks the player doesn't have a vehicle and or vehicle ID

Another error seems to be that we cannot refuel, it does the process but doesn't give any fuel, neither does the emergency refuel. (No errors spat out for this...)

![raw](https://github.com/user-attachments/assets/299f5141-5329-4359-9427-13409f68bb15)

**Comment by my-name-is-samael** [comment]
@KaMiKaZeE1221 
I tried to teleport to a player, to teleport a player to myself, to refuel in a gas station and to refuel with the emergency one.
Everything is working fine on my side.

For the teleportation problem, could you share a stacktrace and a preview of the `PrintObj(BJIContext.Players)` command ?
Is the screenshot about the stacktrace? If so, it seems related to the vehicle configuration screen, what vehicle did you spawn?

For the refuel problem, the mod cannot refill your tank more than the capacity you defined for your vehicle configuration (Vehicle Config > Tuning > Chassis > Fuel Volume). Are you sure your vehicle configuration is allowing more than the quantity after a refuel ?

**Comment by KaMiKaZeE1221** [comment]
ok, so after further testing, the issue was related to code I had in the playermanager.lua to charge you respect points when changing vehicle, it was working fine before the BeamNG update but is now broken, but this is not a BeamJoy issue, sorry to waste your time, but thank you for the reply 🥰

**Comment by my-name-is-samael** [comment]
No problem, happy driving 🤙
