### ISSUE TITLE
Invalid Groups for permissions (v0.34)

### ISSUE THREAD

**Issue by heriklesDM** [my-name-is-samael/BeamJoy#43]
Hello!
When trying to add users to any group I receive the error
`Invalid group "owner" `or `Invalid group "player" ` etc
The command I'm using is
`bj setgroup herikles owner`
The user "herikles" (me) is connected to the server

When joining without a group the server throws an error
`> [LUA ERROR] _BJCOnPlayerConnecting: Resources/Server/BeamJoyCore/managers/PlayerManager.lua:168: attempt to index a nil value (local 'group')`

**Comment by my-name-is-samael** [comment]
@heriklesDM 
I cannot reproduce the error.
Do you applied the latest release and/or did you update from a previous release ?
Could you please share your `BeamJoyData/groups.json` and `BeamJoyData/players/herikles.json` files? (Please remove the IP address in the second, unless your a connecting from your local network)

**Comment by heriklesDM** [comment]
I've solved the issue and it was fully on my part!
I've had a wrong permission setup for my server folder structure (777 is needed, 766 is not enough it seems).
I appologize for wasting your time

**Comment by my-name-is-samael** [comment]
No problem, nice driving 🤙
