### ISSUE TITLE
0.34 error again on modded map

### ISSUE THREAD

**Issue by futuregraphicart** [my-name-is-samael/BeamJoy#46]
i tried to load motorsports playground but its not starting a race the BJI just goes away. thanks for the help.
![error-bji](https://github.com/user-attachments/assets/29030f47-a4b6-4be6-95c3-534b9014e32f)

**Comment by my-name-is-samael** [comment]
Still don't know what is happening here, maybe a concurrent access.
I will release the next version tomorrow with a potential fix.

**Comment by my-name-is-samael** [comment]
@futuregraphicart  I will try something else, it looks pretty similar to the error we had before the 0.34 fix.
What release are you playing on ? Is the error consistent (is it happening every time you join and start a solo race) ? How many start positions are defined in your race ? Is the error happening too if you open the map menu (**M** or `Escape` > `Map`) ?

I will try to create a scenario anti-softlock safe and an anti-softlock for the quicktravel manager too.

**Comment by my-name-is-samael** [comment]
Tested the Motorsports Playground with the last version today, no problem with solo race, but with map menu (I suspect the problem is coming from the map itself)

You can reproduce too typing `gameplay_rawPois.getRawPoiListByLevel("motosports_playground")` in the console, an error is thrown. And the error does not exist if you type `gameplay_rawPois.getRawPoiListByLevel("italy")`.
I will create a system to prevent it with BeamJoy but you should contact the Motorsports Playground mapper for him to fix the issue.

**Comment by futuregraphicart** [comment]
well i rented a dedicated server and it seems to be all working now. i got
players to join and we raced for awhile. there was an error when i joined
motorsports playground but it didnt affect anything. we did have a problem
when players tried to use a modified car i think. anyways thanks for the
help!!! great work. maybe just leave it how it is for now.

**Comment by futuregraphicart** [comment]
im on 0.34 and we had 4-6 start zones.

**Comment by my-name-is-samael** [comment]
I was talking about you BeamJoy version but it is okay. The 1.1.3 just released, please tell me if you still have the issue after patching 🙏

**Comment by futuregraphicart** [comment]
i was on 1.1.2 but now im on 1.1.3. thanks for the updates. i had 8 player
races last night and it was working well for most people. beamng is so
finicky. i can't believe you got all this working!
1-a couple issues with low ram on one pc.
2-the camera going crazy at the start of the countdown for a race and then
sometimes the players camera wont follow the car at the start of a race. i
usually just tell people to hit "c" and it fixes it.
3-not sure if the camera is my fault when clicking camera preview button
when creating up the race.
4-custom tuned cars seemed to break the beamjoy mod too not sure though.
5-maybe an arrow in the current checkpoint aiming to the next checkpoint. i
find making u-turns hard for new players to the map. they dont know where
to go next.
i will do some more testing. sorry if these comments are too tough to
implement haha i know its beamng.
keep up the good work!
bryson
