### ISSUE TITLE
More waypoints then just 3 for hunter gamemode

### ISSUE THREAD

**Issue by coolman5785** [my-name-is-samael/BeamJoy#57]
How can I get more waypoints to show up than just 3 for 3 people in the hunter gamemode?

**Comment by my-name-is-samael** [comment]
Hi,
If you are talking about amount of waypoints hunted must collect to win, there is a number field on the car hunt settings (small window to configure car hunt session where you can configure vehicles configs for instance).
If you are talking about the lack of diversity in start positions and/or waypoints, you can change them and add some in hunter editor (Edit > Hunter)

**Comment by coolman5785** [comment]
![hunter](https://github.com/user-attachments/assets/52221ccf-1bd1-49cd-90c6-c5c6a49816d3)
I don't see where i can change it?

**Comment by my-name-is-samael** [comment]
Oh there is a bug, are you on the latest BeamJoy version?

**Comment by my-name-is-samael** [comment]
Oh ok I understand, there is an interface size issue but the content is here, hidden to the right. You need to enlarge the hunter settings window to the right to make editable fields appear.

![image](https://github.com/user-attachments/assets/80ce19a3-c49a-411e-9de5-c1d506c06697)

I will fix this in the next release (1.1.5)

**Comment by coolman5785** [comment]
Also it says the hunter game mode is disabled, even though I made it "voteable"

**Comment by coolman5785** [comment]
It says the hunter game mode is disabled, even though it's "voteable"

**Comment by my-name-is-samael** [comment]
Yeah I know, there is a bug where the visibility is still off when you have exactly 5 hunters start positions, will be fixed in the next release too, the workaround for now is to have at least 6 hunters start positions.
Sorry for the inconvenience

**Comment by coolman5785** [comment]
Thanks for the help 👍

**Comment by my-name-is-samael** [comment]
Update on the fixed:
Unfortunately, the mod uses the embedded `imgui.CalcTextSize` method which can give weird sizes depending on some factors (charset, length, offset, etc.). I improved the width of columns in every windows but there are still strange sizes (in RU for instance) 😞 

Will be in the 1.1.5
