### ISSUE TITLE
Hunter Mode Configuration options not appearing. 

### ISSUE THREAD

**Issue by TheEndOfNether** [my-name-is-samael/BeamJoy#64]
![image](https://github.com/user-attachments/assets/d0370fe6-5bac-4550-95b2-a9dde7d67d3d)

pretty much the title/image.

**Comment by TheEndOfNether** [comment]
sorry, just saw an earlier post about this. might be good to try and make the ui more compact, or layered though. thanks!

**Comment by my-name-is-samael** [comment]
Already fixed for the next release 👌
