### ISSUE TITLE
Waypoints for races

### ISSUE THREAD

**Issue by KaMiKaZeE1221** [my-name-is-samael/BeamJoy#9]
Technically this is not an issue, rather a request.

I noticed that the Bus missions, delivery missions and so on all use beams default route planner, is there a chance we can also get this for races?

It would make knowing when a corner is coming up a little easier.

**Comment by my-name-is-samael** [comment]
@KaMiKaZeE1221 
I thought about this, problems are:
- For multiple branches, we cannot create multiple routes at once
- If the way is through a one-way street, but the illegal way, the route will search for a road legal path

**Comment by KaMiKaZeE1221** [comment]
> @KaMiKaZeE1221 I thought about this, problems are:
> 
> * For multiple branches, we cannot create multiple routes at once
> * If the way is through a one-way street, but the illegal way, the route will search for a road legal path
> 
> In the upcoming basegame datapack, if you are willing to install it at the time, you would see I worked around this issue with "level design" (placing checkpoints to give visually the way)

Oh ok, yeah I tried a few basic different way to do it myself but my knowledge is pretty minimal. I will definitely give the datapack a go when it released, thank you for still working on this and replying :)
